### ISSUE TITLE
legend takes up a lot of space in trend graphs

### ISSUE THREAD

**Issue by rmm-fcul** [assisi/arena-ui#104]
In the 5x5 arena is is not uncommon to want to monitor 16-25 CASUs.  Trend graphs here dedicate a large fraction of space to the legend, meaning the useable range is reduced drastically. This is exacerbated by the fact that the legend is on the RHS, which is the same side as the new data comes in.

![big_legend_example](https://cloud.githubusercontent.com/assets/7782039/26791441/0291cc08-4a0f-11e7-9daa-60d5562ff8e8.png)
In this example, the useful temperature range is only 24-29C, despite the actual y-range being 24-36C.

Would it be possible to do one of the following?:

- a) make legend text smaller when the number of entries is large
- b) have the legend "roll up" or be (dynamically) hideable somehow
- c) move the legend to the LHS
- (or some other method)

to improve the viewable area?

**Comment by stribor14** [comment]
Right click + Hide legend?
