### ISSUE TITLE
Timestamp format in log files

### ISSUE THREAD

**Issue by plsm** [assisi/arena-ui#105]
Time stamps saved in the logs files are written in scientific notation. The precision of such format does not go up to the seconds. This means that it is impossible to align log data with other data that has timestamps with a precision of seconds.

**Comment by stribor14** [comment]
This was actualy a bug, but is already solved and waiting in pull request #101

EDIT: time stamp was from begining intended to be in seconds since epoch (1.1.1970 00:00) with milisecond precision

**Comment by dmiklic** [comment]
closed by #101
