### ISSUE TITLE
GuI crashes when attempting to plot trend of "Selected CASUs"

### ISSUE THREAD

**Issue by rmm-fcul** [assisi/arena-ui#108]
Plotting a trend graph of a specific field of the selected CASUs, e.g. temp top, is fine.
But the context menu shows options for "Plot selected in same trend"  / "in different trends" even at the top-level "selected CASUS".  
It isn't obvious what it should plot in this case (6 IR plots and 8 temp plots?).  If this is intended, the context menu should indicate something.  If it isn't intended, can the context menu not appear for invalid options? (or be greyed out).

In any case, a crash is not desirable :)

**Comment by dmiklic** [comment]
@stribor14 can you please take a look at this? Seems like disabling the invalid option could be a quick fix.

**Comment by stribor14** [comment]
I think I know where the problem is, will fix it later today
