### ISSUE TITLE
Start/Stop simulator

### ISSUE THREAD

**Issue by stribor14** [assisi/arena-ui#31]
When simulator is started, program releases PID handle so the simulator won't close with GUI. When new instance of GUI is running, action "Stop simulator" does nothing altough a simulator is running.

**Comment by stribor14** [comment]
Current setting is that program does not release PID handle and simulator closes with GUI so "Stop simulator" button can function.

**Comment by dmiklic** [comment]
I don't like this solution. The user can start the simulator, then use it from other code (e.g. Python API). In this case, closing the simulator together with the GUI might not be what the user wants/expects. I think that being unable to close the simulator from the GUI (if the GUI is restarted) is not a problem. I would simply disabe the "Stop simulator" button, if the simulator was not started by the current GUI instance.

**Comment by stribor14** [comment]
- If user closes program, simulator will continue to run (kill by PID can be done only from caller object)

**Comment by stribor14** [comment]
As of commit 7fff3cc in stribor14/new_master, UI can find PID of simulator proces started outside of UI (or in different instance). This enables UI complete control over running simulator process wherever it is started.
