### ISSUE TITLE
"Trend" and "graph" terminology is a bit ambiguous

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#36]
Clean up terminology in context menus referring to trending. The following would make sense:
- a graph refers to the axis on which the data is plotted
- a trend refers to the data itself
- matlab uses the terms plot/axes

Having this in mind, it would be correct to change the context menu in the CASU data treeview to: "Plot selected on same axis"/"Plot selected on different axes"?

**Comment by stribor14** [comment]
Current terminology:
- graph - plotted data from one data source (inherited from QCustomPlot class where QCPGraph item is one line on plot)
- trend - one widget for plotting graphs (from problem definition that trending should be enabled)

ex. one trend can have multiple graphs

**Comment by dmiklic** [comment]
Ok, makes sense, I think this can be closed.
