### ISSUE TITLE
extend all / collapse all button

### ISSUE THREAD

**Issue by mbodi** [assisi/arena-ui#42]
If possible a button in the 'Caus Data' sheet for extending all / collapsing all menu-nodes

**Comment by dmiklic** [comment]
Do you mean expand/collapse all nodes of a single CASU, or all nodes of all CASUs?

**Comment by mbodi** [comment]
good question. The idea for this button comes from the scenario, that if you want to see the trend-graphs of the temperature sensors, you have to click a lot to get to the senosor values of all CASUs. 

So I would say all nodes, of all CASUs.  

But this has very low priority, and we should think about, how feasable this will be for 60 CASUs

**Comment by stribor14** [comment]
Maybe to enable user to select CASUs for which he wants action to be done?

**Comment by stribor14** [comment]
Is this feature still needed with addition of group tree view? If not, issue should be closed.

**Comment by dmiklic** [comment]
Group treeview (#58) provides superior functionality to achieve the same goal. Closing.
