### ISSUE TITLE
Vibration setpoint OFF not working

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#44]
Selecting ON, 0, 0 stops the vibration, but OFF, 0, 0 does not have any effect.

**Comment by stribor14** [comment]
I've read code responsible for this, UI sends message as expected. This seems to be bug on the other end.

**Comment by dmiklic** [comment]
Seems to be a simulator issue. Opened as larics/assisi-playground#85

**Comment by dmiklic** [comment]
Reopening this after testing in Graz. Calling `Casu.speaker_standby()` successfully stops vibration, whereas sending the OFF command through the GUI fails to stop vibration (even if amplitude and frequency setpoints are manually set to 0).

**Comment by stribor14** [comment]
![screenshot from 2016-09-16 14-10-09](https://cloud.githubusercontent.com/assets/10760409/18585473/64b2c12e-7c17-11e6-826d-d75776ebe73a.png)

It sends message acording to:
http://assisipy.readthedocs.io/en/latest/protocol.html

**Comment by dmiklic** [comment]
@marselap we need to take a look at this once we have a fully functional CASU assembled in zagreb.

**Comment by stribor14** [comment]
@dmiklic tested on real CASU -> it works

**Comment by stribor14** [comment]
This one should be closed (@dmiklic)
