### ISSUE TITLE
restore scrolling on trend graphs

### ISSUE THREAD

**Issue by rmm-fcul** [assisi/arena-ui#46]
By default, a trend graph scrolls along as new data arrives.  However, if you use the mouse to drag where the image is centred, the trend time limits stay fixed (i.e. new data gets drawn off the RHS of the screen).  

Is it possible to add a button or context menu option to restore scrolling with the latest data?

**Comment by stribor14** [comment]
Mouse controls for trend graphs:
- **Click + mouse drag** -> reposition graph and stop realtime graph adjusting (so you can study part that you want)
- **Ctrl + mouse scroll** -> y-axis zoom
- **Shift + mouse scroll** -> x-axis zoom
- **mouse scroll** -> x-axis & y-axis zoom
- **double click** -> resume realtime graph adjusting

When realtime graph adjusting is ON, x-axis scrolls with new data while y-axis tries to adjust itself so no data goes out of bounds

**Comment by rmm-fcul** [comment]
Great, thanks for the info.  Can you put this into the docs - probably this (https://github.com/larics/assisi-arena-ui/blob/master/userdoc/source/trends.rst) to close the issue? most of the controls are explained but not the restoring of realtime adjustment. (although actually this list is very concise and would make a good addition to the "monitoring and manipulating data trends" section).
