### ISSUE TITLE
Temperature sensor graphics

### ISSUE THREAD

**Issue by stribor14** [assisi/arena-ui#50]
With new graphics markers for various sensors, temperature sensors should not move closer to CASU when IR sensor is hidden. This causes temp marker to be drawn on similar distance as vibration marker

**Comment by dmiklic** [comment]
+1

**Comment by dmiklic** [comment]
Temp markers shoul be at 1.5 cm from CASU body edge (2.5 cm from CASU center). CASU diameter is 2 cm.
