### ISSUE TITLE
Unnecessary / characters appended to items inside the Settings dialogs

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#52]
Every time the dialog is closed (by clicking on OK) and re-opened, an additional / character is added to all paths in the dialog.

**Comment by stribor14** [comment]
That is how folder paths in program are stored. Program checks if selected path is folder only once (when change is applied) and if path is in correct format to use it through rest of the program (it needs '/' at the end so later it only calculates file name and adds it to a folder path before opens/creates wanted file)
