### ISSUE TITLE
Actuator setpoint dialogs need default values

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#54]
Whenever a dialog is opened, the editable fields should be pre-populated with current setpoints (or default values if no setpoints are currently active, or the dialog is activated for a group of CASUs). This saves time when working with actuators that take several parameters (e.g. vibration).

**Comment by stribor14** [comment]
What values should be default if there is currently no active setpoints (or group is selected)?

**Comment by dmiklic** [comment]
In these two cases, it can be whatever. For consistency, i propose it's the lower limit of allowed values, and OFF for all actuators.
