### ISSUE TITLE
Add dialog for setting vibration patterns

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#55]
Add a dialog option for specifying vibration pattern setpoints.

**Comment by stribor14** [comment]
example: [1000,100],[500,1],[50,0]

**Comment by stribor14** [comment]
Should be closed when fully implemented (after #96)

**Comment by stribor14** [comment]
@dmiklic  I think utils.h/.cpp is surplus

**Comment by dmiklic** [comment]
@stribor14 can we remove utils.h/.cpp?
