### ISSUE TITLE
Update user docs with new UI features

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#56]
The user docs should be updated to reflect the new stimulus markers and other enhancements.

**Comment by dmiklic** [comment]
@stribor14 this is the last major change before freezing development

**Comment by stribor14** [comment]
You can close this one :) forgot to reference it in commit message

**Comment by dmiklic** [comment]
Closed in 38bfac61f32a80fc3d4972342fcd7de9492feab3
