### ISSUE TITLE
Create additional treeviews for CASU groups

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#58]
Very often, groups are created with the aim of manipulating several CASUs in the same way, e.g. sending trending the same sensor reading from several CASUs. However, in the current implementation, the user still has to expand each individual treeview for every CASU and select the data to plot. One wrong click (i.e. click without having the control key properly pressed) can ruin the whole selection. This problem will become far worse as the number of CASUs increases.

A solution to this problem is to create an additional treeview item for the group. An action performed on an element of this treeview would be applied to all CASUs. @stribor14 please comment wheather you think that this approach is feasible.

**Comment by stribor14** [comment]
For manipulating same CASU group without worry of losing selection, user can group them with Ctrl+G or by icon on left shortcut tray (those item groups are even saved when user saves project and loads it later) and later ungrouo them with Ctrl+U. Also, groups can be subsegments of other groups (ex. group contains 2 CASU items and one subgroup which was created before from 3 CASU items; this results in group of 5 CASU items which when ungrouped reverts to 2 individual CASUs and one group of 3 CASUs)

What exactly do you mean by "action performed on element of additional treeview"? For example, if user clicks to plot front temperature sensor, that should be applied to all front temp sensors in this group? Which action will benefit from this?

If it is only for faster expanding of tree view, it is already planned in issue #42 for user to be able to select CASUs in tree view and expand/colapse them with additional buttons

**Comment by dmiklic** [comment]
The typical use case that requires this is the following:

User selects a group of CASUs and wants to plot the reading of the TEMP_WAX sensor for all CASUs in the group, on the same graph. This is a very common use case and is currently quite tedious to do (requires individually selecting the sensor for every casu), even with 9 CASUs (and we will eventually have to do it for 64 CASUs :)

@rmm-fcul please comment if I misunderstood/forgot something.

**Comment by rmm-fcul** [comment]
@dmiklic the description is good - should apply to any property that is common to all the nodes in a selected group. And since making groups is easy, this will be a big improvement in usability for the repetitive tasks

@stribor14 

> For example, if user clicks to plot front temperature sensor, that should be applied to all front temp sensors in this group? 

yes, precisely.  After a group is formed, there should be, for example a "front temp" group entry, which would allow "add trend to graph" for all nodes in the group.  Then it should be easy to make this graph, and also a bit later if needed, a trend graph of all "pcb temp" in the group could take just a couple of clicks (sorry sensor names aren't precise here).
