### ISSUE TITLE
The logic of IR readings is inverted

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#59]
The raw reading reports the amount of IR light reflected back to the sensor. When this value is small, this means that there is no object nearby and the visualization symbol should be "long". When the value is large, there is an object nearby, so the visualization symbol should be "short".

There is an additional problem due to the fact that IR readings in the simulator are not properly scaled, i.e., they do not correspond well to real IR sensor readings (real readings are approximately in the 2000-70000 range). This is reported in larics/assisi-playground#9

**Comment by dmiklic** [comment]
On the other hand, the current visualization seems very useful for debugging malfunctioning proximity sensors, so we should leave it as it is for now.

**Comment by stribor14** [comment]
I thought about this issue and have come to conclusion that inverting sensor reading and graphic marker is more intuitive for graphic representation (if there is nothing, no marker is shown). I went with similar logic as parking sensor on cars (if object is closer, sound signal is more annoying). 

Other thing to consider was to decrease and minimize number of objects shown at once with purpose of increasing visibility of information when lots of CASUs are shown.

**Comment by rmm-fcul** [comment]
> There is an additional problem due to the fact that IR readings in the simulator are not properly scaled, i.e., they do not correspond well to real IR sensor readings (real readings are approximately in the 2000-70000 range). This is reported in larics/assisi-playground#9

The IR values that we see in the lab are in the range ~2000-65279 (probably 2^16 is the upper limit).  If the visualisation is scaled so the maximum reading of one CASU does not overlap on the next, this would make it much more user-friendly.  (See screenshot below)

![screenshot from 2016-08-16 20-43-18](https://cloud.githubusercontent.com/assets/7782039/17711498/379d13d4-63f2-11e6-95c4-b7abb1e8dfb0.png)

**Comment by stribor14** [comment]
That will be easy fix, I'll do it next thing in the morning. I didn't know range and simulator was giving max cca 4000. IR Marker will not go outside of temperature marker.

**Comment by rmm-fcul** [comment]
Thanks. 
Yes, I recall being surprised at the big mismatch in typical values.  I just checked and in the simulator the max reading of all sensors is set to 3731.  

@dmiklic should the simulator provide values in the same 16 bit range? Do we know of any other consequences of the absolute IR sensor values?

**Comment by dmiklic** [comment]
@stribor14 I'll make this fix, because I have access to the real CASUs, so it will be easier for me to test and tweak.

@rmm-fcul yes, the simulator should provide similar values to the real CASUs; the change to the simulator might be a bit bigger (possibliy we'll need to override the whole IR model), so It might take a while
