### ISSUE TITLE
add capability to zoom in on the arena

### ISSUE THREAD

**Issue by rmm-fcul** [assisi/arena-ui#62]
the subwindow displaying the arena is of fixed size; and the size of the arena within this window is also fixed.  It would be helpful to be able to zoom into the arena; and the space could be used more efficiently - especially for low resolution monitors.

In addition, it could help with interactive viewing of sensor readings and noticing errors

**Comment by stribor14** [comment]
@dmiklic can I use 3rd party solution from stackoverflow?
http://stackoverflow.com/questions/19113532/qgraphicsview-zooming-in-and-out-under-mouse-position-using-mouse-wheel

Other 3rd party solutions had GPL license. (QCustomPlot & FlowLayout)

**Comment by dmiklic** [comment]
Of course, as long as it works correctly :) 

However, if the GPL-licensed code works better, use it by all means. We'll just [relicense ](http://programmers.stackexchange.com/questions/66254/can-a-user-relicense-lgpl-as-gpl-or-gpl-as-agpl)our code.

**Comment by stribor14** [comment]
Zoom & scroll modifiers:
- Ctrl + mouse wheel = zoom in/out
- mouse wheel = vertical scroll
- Shift + mouse wheel = vertical scroll (2x speed)
- Alt + mouse wheel = horizontal scroll
- Shift + Alt + mouse wheel = horizontal scroll (2x speed)
