### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by stribor14** [assisi/arena-ui#72]
Qt5Gstreamer support
GCC 5.1 support (c++14)
- auto lambda parameters
- lambda capture expressions
- decltype(auto) - can detect if reference type or not
- tuple addressing via type (future ideas)

**Comment by stribor14** [comment]
Move to Qt 5.6 or newer (Ubuntu 16.04 default is 5.5)
https://wiki.qt.io/Install_Qt_5_on_Ubuntu
- Qt5 connect style with QMenu::addAction (can use lambda expressions)

this will result in more compact code

**Comment by dmiklic** [comment]
I would hold off the Qt upgrade unless the QMenu::addAction feature is absolutely essential. If essential UI functionality can be achieved without it, then it does not justify the added complexity of manual installation (and maintainance) of the Qt framework.

**Comment by stribor14** [comment]
This one is closed by PR #82 (@dmiklic)
