### ISSUE TITLE
Adding trends from the treeview adds incorrect data buffers

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#79]
The plotted data is incorrect in several ways:
- when e.g. "Temp - WAX" is selected, right-click->Plot selected in same trend will plot "Temp - F" and "Temp - L"
- plotting "IR - F" will plot "IR - F" and "Temp - F"
- when there is a group selected, the behavior is even weirder: sometimes the correct values are plotted, but an additional variable is plotted

**Comment by stribor14** [comment]
1.  Fixed (wrong legend names for some buffers)
2. couldn't reproduce, perhaps both were selected? (then this is what should happen, both selected buffers plotted in trend) -> could add if branch is collapsed to deselect its members if it would help
3. Currently cross-selection between casu&group trees is allowed, so perhaps some data remained selected in casu tree? (this was intentional)

**Comment by dmiklic** [comment]
1. ok
2. collapsed branches should automatically be deselected, otherwise the behavior is not really intuitive; also, deselecting is now done by clicking on the parent branch, it would be more intuitive if the first click on an item selects, the second one deselects
3. Not sure about this one, it is not completely intuitive to me. I'd rather disable this feature.

**Comment by stribor14** [comment]
not sure what is happening in 2nd issue (I couldn't reproduce bug): 
- multiple selection is only possible with Ctrl modifier -> OK
- item remains selected after branch collapsing, it is deselected if user selects another one (without Ctrl modifier) ->this helps if user wants cherry-pick multiple items for plotting across many CASUs, he can collapse current branch and expand another (he must use Ctrl) -> Ok
- if item is selected and clicked again, it is reselected (if multiple selected, and items is clicked without Ctrl, only this item will remain selected) -> QTreeView behaviour, and I think this is as expected (consistent selection behaviour through common applications across various platforms) -> Ok

For the 3rd issue I propose 2 solutions:
1. deselect everything if user selects something in other tree
2. as 1st, but add Ctrl modifier between treeViews (user could still mix items, but only with Ctrl)

**Comment by dmiklic** [comment]
Closed by 85b4662
