### ISSUE TITLE
Add "Apply" button to actuator setpoint dialogs

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#84]
Sometimes it is necessary to try out several setpoints in a row. Having an "Apply" button would make this easier, i.e., one would not need to go through the whole setpoint dialog opening procedure, which can be a bit cumbersome.

**Comment by stribor14** [comment]
Implemented in commit e27f3c6

EDIT: @dmiklic Should've been closed after pull request (forgot to close it through commit comment)

**Comment by dmiklic** [comment]
Definitely closed by 56a04d073838954213684547201fce5872a09f0b

**Comment by dmiklic** [comment]
Definitely closed by 56a04d073838954213684547201fce5872a09f0b
