### ISSUE TITLE
Split logs by device

### ISSUE THREAD

**Issue by dmiklic** [assisi/arena-ui#91]
Do this either on creation, i.e., in the UI code, or later using assisipy tools.

Should we also split logs by CASUs? Or not?

**Comment by stribor14** [comment]
should this be implemented?
Simple code change could make individual logs for each casu in same subfolder (subfolders are sorted by date/time already)

**Comment by stribor14** [comment]
Idea is split logs by sensors. Proposed hierarchy:

- LOGS_DIR
  - DATE_DIR
    - CASU_DIR
      - SENSOR_DIR
        - TIME_LOG
