### ISSUE TITLE
Graph colors suboptimal

### ISSUE THREAD

**Issue by marselap** [assisi/arena-ui#93]
Please remove the white color from color set for the graphs. This one is invisible if not selected. 

Also, after a certain number of different colors, all become black and indistinguishable if not selected.

**Comment by stribor14** [comment]
what is number of colors you think would be appropriate? Currently there is 13 colors (for example, matlab has 6+b&w)

Few ideas:

1. Random generate #rrggbb
2. use color list from X11

both ideas cannot guaranty visual difference (even though they would have different values)

**Comment by dmiklic** [comment]
I would prefer random picks from the [X11 color list](http://cng.seas.rochester.edu/CNG/docs/x11color.html) **skipping** LavenderBlush (#FFF0F5), GhostWhite (#F8F8FF), AliceBlue (#F0F8FF), Azure (#F0FFFF), MintCream (#F5FFFA), Honeydew (#F0FFF0), Ivory (#FFFFF0), LightYellow (#FFFFE0), Cornsilk (#FFF8DC), FloralWhite (#FFFAF0), Linen (#FAF0E6), Seashell (#FFF5EE), Snow (#FFFAFA), White (#FFFFFF) and WhiteSmoke (#F5F5F5)

**Comment by stribor14** [comment]
Instead of X11 color names, I used SVG color names (more universal). There are currently 121 colors enabled.
